#注册中心http basic安全配置，
registry-security:
  #用户名
  username: root
  #密码
  password: root
  #加密器id，查看PasswordEncoderFactories
  id: noop
spring:
  application:
    #eureka 服务名
    name: registry-center
  cloud:
    inetutils:
      ignored-interfaces:
          - Dell.*
          - VMware.*
          - vEth.*
          - Hyper.*
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      user.name: ${monitor-security.username:any}
      user.password: ${monitor-security.password:any}
  server:
    #单机情况下启用会导致页面红色提示。
    #自我保护模式，默认情况下在90秒内收不到其他eureka server的心跳时会开启。
    enable-self-preservation: false
  #client单机设置
  client:
    #注册成为服务
    register-with-eureka: true
    #检索服务
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: first
eureka:
    instance:
      hostname: eureka-first
    client:
      service-url:
        defaultZone: http://${registry-security.username}:${registry-security.password}@127.0.0.1:7002/eureka,http://${registry-security.username}:${registry-security.password}@127.0.0.1:7003/eureka
server:
  port: ${port:7001}
---
spring:
  profiles: second
eureka:
    instance:
      hostname: eureka-second
    client:
      service-url:
       defaultZone: http://${registry-security.username}:${registry-security.password}@127.0.0.1:7001/eureka,http://${registry-security.username}:${registry-security.password}@127.0.0.1:7003/eureka
server:
  port: ${port:7002}
---
spring:
  profiles: third
eureka:
    instance:
      hostname: eureka-third
    client:
      service-url:
       defaultZone: http://${registry-security.username}:${registry-security.password}@127.0.0.1:7001/eureka,http://${registry-security.username}:${registry-security.password}@127.0.0.1:7002/eureka
server:
  port: ${port:7003}